- name: Fish | Install
  homebrew:
    name: fish
    state: present

- name: Fish | Install Starship
  homebrew:
    name: starship
    state: present

- name: Fish | Add to /etc/shells
  lineinfile:
    line: /usr/local/bin/fish
    dest: /etc/shells
    state: present
  register: fish_shells
  become: true
  become_method: sudo

- name: Fish | Update Default Shell
  command: chsh -s /usr/local/bin/fish
  when: fish_shells.changed
