- import_tasks: macos.yml
  when: ansible_os_family == "Darwin"

- name: Fish | Link config.fish
  file:
    src: '{{ dotfiles_home }}/roles/fish/files/config.fish.link'
    dest: '{{ dotfiles_user_home }}/.config/fish/config.fish'
    state: link
    force: yes

- name: Fish | Link starship.toml
  file:
    src: '{{ dotfiles_home }}/roles/fish/files/starship.toml.link'
    dest: '{{ dotfiles_user_home }}/.config/starship.toml'
    state: link
    force: yes

- name: Fish | Link completions
  file:
    src: '{{ item.src }}'
    dest: "{{ dotfiles_user_home }}/.config/fish/completions/{{ ((item.path | splitext)[:-1] | join('.')) }}"
    state: link
    force: yes
  with_filetree: completions/

- name: Fish | Link functions
  file:
    src: '{{ item.src }}'
    dest: "{{ dotfiles_user_home }}/.config/fish/functions/{{ ((item.path | splitext)[:-1] | join('.')) }}"
    state: link
    force: yes
  with_filetree: functions/
