#!/bin/sh

echo | xargs -n 1 code --install-extension <<- EOF
alexcvzz.vscode-sqlite
bungcip.better-toml
codezombiech.gitignore
dbaeumer.vscode-eslint
DotJoshJohnson.xml
eamodio.gitlens
eg2.vscode-npm-script
esbenp.prettier-vscode
foxundermoon.shell-format
HookyQR.beautify
Kasik96.swift
mikestead.dotenv
mischah.relaxed-theme
ms-python.python
ms-vscode.csharp
ms-vscode.Go
ms-vsliveshare.vsliveshare
msjsdiag.debugger-for-chrome
rebornix.ruby
rust-lang.rust
skyapps.fish-vscode
timonwong.shellcheck
twxs.cmake
vadimcn.vscode-lldb
wingrunr21.vscode-ruby
yzhang.markdown-all-in-one
EOF
