- name: Update Homebrew
  homebrew:
    update_homebrew: yes
  when: package_update

- name: Upgrade Homebrew Formulae
  homebrew:
    upgrade_all: yes
  when: package_upgrade

- name: Install Homebrew Taps
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items: '{{ macos_homebrew_taps }}'

- name: Install Homebrew Formulae
  homebrew:
    name: '{{ macos_homebrew_formula }}'
    state: present

- name: Install Homebrew Casks
  homebrew_cask:
    name: '{{ macos_homebrew_casks }}'
    state: present
