- name: Visual Studio Code | Install
  homebrew_cask:
    name: visual-studio-code
    state: present

- name: Visual Studio Code | Link settings.json
  file:
    src: '{{ dotfiles_home }}/roles/vscode/files/settings.json.link'
    dest: '{{ dotfiles_user_home }}/Library/Application Support/Code/User/settings.json'
    state: link
    force: yes
