- name: Node.js | Install asdf Node.js plugin
  command: asdf plugin add nodejs
  register: nodejs_add
  changed_when: nodejs_add.rc == 0
  failed_when: nodejs_add.rc == 1

- name: Node.js | Import release team keyring
  command: '{{ asdf_dir }}/plugins/nodejs/bin/import-release-team-keyring'
  register: nodejs_import_keys
  changed_when: '"unchanged: 0" in nodejs_import_keys.stdout'

- name: Node.js | Install tool version
  command: asdf install nodejs
  register: nodejs_install
  changed_when: '"is already installed" not in nodejs_install.stdout'
