- name: Check if this is a supported Linux
  fail:
    msg: This role cannot be run on any distro not derived from either Debian or Red Hat Linux.
  when: ansible_facts['os_family'] != "Debian" and ansible_facts['os_family'] != "RedHat"

- import_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- import_tasks: redhat.yml
  when: ansible_facts['os_family'] == "RedHat"
