- name: asdf | Install
  homebrew:
    name: asdf
    state: present
  when: ansible_facts['os_family'] == "Darwin"

- name: asdf | Install
  git:
    repo: git@github.com:asdf-vm/asdf.git
    dest: '{{ asdf_dir }}'
    version: '{{ asdf_version }}'
    clone: yes
    update: yes
    force: yes
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"
