- import_tasks: macos.yml
  when: ansible_os_family == "Darwin"

- name: Link global gitignore file
  file:
    src: .gitignore_global.link
    dest: '{{ dotfiles_user_home }}/.gitignore_global'
    state: link
    force: yes

- name: Write gitconfig
  template:
    src: gitconfig.j2
    dest: '{{ dotfiles_user_home }}/.gitconfig'
    mode: '0600'
