- name: Java | Install asdf Java plugin
  command: asdf plugin add java
  register: java_add
  changed_when: java_add.rc == 0
  failed_when: java_add.rc == 1

- name: Java | Install tool version
  command: asdf install java
  register: java_install
  changed_when: '"is already installed" not in java_install.stdout'
