- name: Ruby | Install asdf Ruby plugin
  command: asdf plugin add ruby
  register: ruby_add
  changed_when: ruby_add.rc == 0
  failed_when: ruby_add.rc == 1

- name: Ruby | Install tool version
  command: asdf install ruby
  register: ruby_install
  changed_when: '"is already installed" not in ruby_install.stdout'
